---
- hosts: desktops
  become: True
  ignore_unreachable: True
  roles:
    - role: alyxxy-base
    - role: alyxxy-kde
    - role: alyxxy-desktop

- hosts: surface-book2
  become: True
  ignore_unreachable: True
  roles:
    - role: alyxxy-surface
